version: "3.9"
services:

  mongodb:
    image: mongo:7.0
    hostname: mongodb
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
      - "${MONGO_PORT2}:37017"
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
    env_file:
      - .env

  mongodb-seed:
    image: mongo:7.0
    hostname: mongodb-seed
    container_name: mongodb-seed
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./mongodb/data/:/data
    command: /bin/bash -c "mongoimport  --host=mongodb -d exercises -c foo --file=/data/foo.json --jsonArray &&
      mongorestore --host=mongodb -d exercises -c restaurants /data/restaurants.bson &&
      mongorestore --host=mongodb -d exercises -c games /data/games.bson &&
      mongorestore --host=mongodb -d exercises -c yelp-business /data/yelp-business.bson"
    env_file:
      - .env

  neo4j:
    image: neo4j:5.24
    hostname: neo4j
    container_name: neo4j
    volumes:
      - ./neo4j/data:/datasets
    ports:
      - "${NEO4J_PORT}:7687"
      - "${NEO4J_PORT_GUI}:7474"
    env_file:
      - .env
